### ISSUE TITLE
Remaining CTT Migration tasks

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/champ-transformation-tool#3]
I have just moved the CTT code and documentation to GitHub from BitBucket and Google Sites respectively. The remaining tasks in this migration require various admin privileges related to these historical services:

1. Empty the Google Sites site of content and just have a single hyperlink to the [GH pages site](https://riverscapes.github.io/champ-transformation-tool/index.html).
1. Switch DNS forwarding from the old Google site to the new GitHub Site.
1. Make the BitBucket repo private so folks don't use it any more. I recommend leaving it on BB for a while as a backup.

**Comment by joewheaton** [comment]
@philipbaileynar  is a dope

**Comment by joewheaton** [comment]
Thanks @philipbaileynar. I completed 1 (following your lead... you left out the [readme](http://ctt.riverscapes.xyz/instructions) page).  I've also taken care of 2. I'm not too worried about 3.  I did update the links though...
